[Q]
Qa
Qe
Qi
Qo
Qu

[W]
Wa
We
Wi = "Với"
Wo
Wu

[E]
Eq
Ew
Er
Et
Ey
Ep
Es
Ed
Ef
Eg
Eh
Ej
Ek
El
Ez
Ex
Ec
Ev
Eb
En
Em

[R]
Ra
Re
Ri
Ro = "Phát âm"
Ru

[T]
Ta = "Xúc giác"
Te
Ti
To
Tu

[Y]
Ya
Ye
Yi
Yo
Yu

[U]
Uq
Uw
Ur
Ut
Uy
Up
Us
Ud
Uf
Ug
Uh
Uj
Uk
Ul
Uz
Ux
Uc
Uv
Ub
Un
Um

[I]
Iq
Iw
Ir
It
Iy
Ip
Is = "Là"
Id
If
Ig
Ih
Ij
Ik
Il
Iz
Ix
Ic
Iv
Ib
In = "Đang"
Im

[O]
Oq
Ow
Or
Ot
Oy
Op = "Trái nghĩa"
Os
Od
Of
Og
Oh
Oj
Ok
Ol
Oz
Ox
Oc
Ov
Ob
On
Om

[P]
Pa = "Quá khứ"
Pe = "Chỉ người"
Pi
Po
Pu

[A]
Aq
Aw
Ar
At
Ay
Ap
As
Ad
Af
Ag
Ah
Aj
Ak
Al
Az
Ax
Ac
Av
Ab
An = "Và"
Am

[S]
Sa
Se
Si
So
Su

[D]
Da
De
Di
Do
Du

[F]
Fa
Fe
Fi
Fo
Fu = "Tương lai"

[G]
Ga
Ge
Gi
Go
Gu

[H]
Ha
He = "Thính giác"
Hi
Ho
Hu

[J]
Ja
Je
Ji
Jo
Ju

[K]
Ka
Ke
Ki
Ko
Ku

[L]
La
Le
Li
Lo
Lu

[Z]
Za
Ze
Zi
Zo
Zu

[X]
Xa
Xe
Xi
Xo
Xu

[C]
Ca
Ce
Ci
Co
Cu

[V]
Va
Ve
Vi = "Thị giác"
Vo
Vu

[B]
Ba
Be = "Của"
Bi
Bo
Bu

[N]
Na
Ne
Ni
No
Nu

[M]
Ma
Me = "Khứu giác"
Mi
Mo = "Chuyển động"
Mu = "Nhiều"