["Câu, Từ Và Nghĩa"]

Rigop = "Tối"
"Timrig(tim-rig)" = "Ban ngày"
"Tim rigop" = "Ban đêm"
"Ian u" = "Tôi và bạn"
"Wankas(wan-kas)" = "Muốn hỏi"
"Sag bodvi" = "Mắt"
"Sag bodta" = "Da"
"Sag bodme" = "Mũi"
"Sag bodro" = "Miệng"
"Sag bodhe" = "Tai"
"Hel u! I wankas(wan-kas)" = "Xin chào bạn! Tôi muốn hỏi"
"Retmov(ret-mov)Ret movmo" = "Động vật"
"Rettan(ret-mov)/Ret tanmo" = "Thực vật"
"Tarmar(tar-mar)" = "Trí tuệ nhân tạo"
"Uistarmar(u-is-tar-mar)" = "Bạn là trí tuệ nhân tạo"
"Meclif(mec-lif)" = "Máy bay"
"Mēclif(mēc-lif)" = "Siêu máy bay."
"Meclifdan(mec-lif-dan)" = "Máy bay chiến đấu"
"(Her/hes)roac" = "Hành động nói"
"(Her/hes)ro" = "Nói"
Herro = "Anh ấy nói"
"Hotrig/Fir" = "Lửa"
Worpe = "Công nhân"
"Cac timlo/Cacsef(cac-sef)" = "Nhà"
"Mecronbig(mec-ron-big) fasmo" = "Xe hơi/Xe to"
"Mecron(mec-ron) bigop fasmoop" = "Xe đạp/Xe thô sơ"
"Mecron bigop fasmo" = "Xe máy"
"Worpe lif" = "Phi công"
"Cacrec(cac-rec)/Cacretrec(cac-ret-rec)" = "Bệnh viện"
"Winmuan big/Wīnmu" = "Bão/Bão lớn/Siêu bão"
"Cacmēcliffas/Cacmēclif" = "Sân bay"
"Gopfās" = "Chạy"