["Thông Tin"]
"Tên" = "Krypton"
"Mô Tả" = "Conlang"

["Ngữ Âm"]
"Nguyên Âm(V)" = "A, E, I, O, U"
"Phụ Âm(C)" = "Q, W, R, T, Y, P, S, D, F, G, H, J, K, L, Z, X, C, V, B, N, M"

["Cấu Trúc"]
"Từ" = "CVC, V"
"Phụ Tố(A)" = ["CV, VC", "Từ(A)(A)...", "Phụ tố này không ảnh hưởng đến phụ tố khác, chỉ ảnh hưởng đến từ đứng trước(từ gốc)"]
"Tiền Tố" = "Không có"
"Hậu Tố" = "Giữ nguyên nghĩa"
"SVO" = ""
"Ghép Từ" = [
    "Chỉ những từ không có phụ tố mới được ghép với nhau, nếu có phụ tố phải dùng dấu - để phân biệt giữa các từ",
    "Có thể viết tách ra, không ghép lại nếu muốn. Không bắt buộc ghép từ"
]

["Bảng số phụ tố"]
"Số" = "Q(01), W(02), E(03), R(04), T05), Y(06), U(07), I(08), O(09), P(10), A(11), S(12), D(13), F(14), G(15), H(16), J(17), K(18), L(19), Z(20), X(21), C(22), V(23), B(24), N(25), M(26)"
"Tính Vị Trí Của Phụ Tố" = "(Ko → K=18, O=09 → 1809, Ud → U=07, d=13 → 0713) → 1809 > 0713(1809 lớn hơn nên đứng trước) → Koud(Ko-ud)"

["Biến thể nguyên âm"]
Umlaut = "Ä, Ë, Ï, Ö, Ü: Vi mô lại ý nghĩa của từ gốc"
Macron = "Ā, Ē, Ī, Ō, Ū: Vĩ mô hơn ý nghĩa của từ gốc"