#Language: 

[T]
Ta = "Xúc giác"
Te = "Thực tế/Là gì"
Ti = "Nhỏ"
To = "Từng phần"
Tu = "Thường xuyên"

[I]
Is = "Là"
In = "Đang"
Iq = "Có thể là"
It = "Có vẻ"
Iw = "Chắc chắn"

[O]
Op = "Trái nghĩa"
Or = "Hay là"
Os = "Trong trạng thái"
Ot = "Kết thúc"
Ow = "Lặp lại"

[P]
Pa = "Quá khứ"
Po = "Phát âm"
Pe = "Chỉ người"
Pi = "Liên quan"
Pu = "Có thể"

[A]
An = "Và"
Ac = "Hành động"
Ad = "Thêm/Cộng"
Al = "Nhất định"
Aw = "Cảnh báo"

[S]
Se = "Khứu giác"
Si = "Kích thước"
So = "Nguồn gốc"
Sa = "Thừa"
Su = "Ngoại lệ"

[F]
Fu = "Tương lai"
Fe = "Thường xuyên"
Fi = "Kết thúc"
Fo = "Lực"
Fa = "Chính thức"

[H]
He = "Thính giác"
Hi = "Cao độ"
Ho = "Tách biệt"
Ha = "Mở rộng"
Hu = "Nhân tạo"

[V]
Vi = "Thị giác"
Vo = "Giọng/Lồng tiếng"
Va = "Giá trị"
Vu = "Chuyên sâu"
Ve = "Liên kết"

[B]
Be = "Của"
Bi = "Cạnh"
Ba = "Lại"
Bo = "Khía cạnh"
Bu = "Quanh"

[N]
Ne = "Phủ định"
Ni = "Trong"
No = "Số lượng"
Na = "Không hoàn toàn"
Nu = "Mới"

[M]
Mu = "Nhiều"
Mo = "Chuyển động"
Me = "Độ đo"
Mi = "Giữa"
Ma = "Bí mật/Riêu tư"

[E]
Er = "Tác nhân (người/vật làm)"
El = "Liên quan đến"
Em = "Nhấn mạnh"
En = "Biến thành"
Ew = "Kiểu/Phong cách"

[L]
Le = "Nhỏ/Giảm"
Li = "Giống"
Lo = "Để/Mục đích"
La = "Xa"
Lu = "Độc lập"

[R]
Re = "Lại/Nhắc lại"
Ri = "Ngược lại"
Ro = "Vòng tròn"
Ra = "Hướng/Chiều"
Ru = "Động lực"

[D]
Do = "Kép/Đôi"
Di = "Khác biệt"
De = "Hạ/Giảm"
Da = "Cho phép"
Du = "Động"

[C]
Ce = "Tập trung"
Co = "Kết nối"
Ca = "Nguyên nhân"
Ci = "Vòng/Chu kỳ"
Cu = "Cắt ngắn"

[G]
Ga = "Tăng"
Go = "Đi"
Ge = "Thế hệ"
Gi = "Quà tặng"
Gu = "Xoay"

[K]
Ka = "Khóa"
Ko = "Ổn định"
Ke = "Giữ"
Ki = "Sắc cảnh"
Ku = "Biết"

[W]
Wa = "Cảnh báo"
We = "Mặc dù"
Wi = "Rộng"
Wo = "Tệ hơn"
Wu = "Yếu"

[J]
Ja = "Tổng hợp"
Jo = "Nối"
Je = "Đồ"
Ji = "Hành trình"
Ju = "Công lý"

[X]
Xa = "Phức tạp"
Xo = "Ngoại lệ"
Xe = "Chính xác"
Xi = "Phóng to"
Xu = "Xu hướng"

[Z]
Za = "Tổ chức"
Zo = "Khu vực"
Ze = "Không"
Zi = "Zip/Nén"
Zu = "Phần tử"

[Q]
Qa = "Câu hỏi"
Qo = "Đóng"
Qe = "Trình độ"
Qi = "Yên tĩnh"
Qu = "Lượng tử"

[Y]
Ya = "Năng"
Yo = "Năng lượng"
Ye = "Có lẽ"
Yi = "Năng suất"
Yu = "Dễ dàng"
