[Q]

Qaq
Qaw
Qar
Qat
Qay
Qap
Qas
Qad
Qaf
Qag
Qah
Qaj
Qak
Qal
Qaz
Qax
Qac
Qav
Qab
Qan
Qam

Qeq
Qew
Qer
Qet
Qey
Qep
Qes
Qed
Qef
Qeg
Qeh
Qej
Qek
Qel
Qez
Qex
Qec
Qev
Qeb
Qen
Qem

Qiq
Qiw
Qir
Qit
Qiy
Qip
Qis
Qid
Qif
Qig
Qih
Qij
Qik
Qil
Qiz
Qix
Qic
Qiv
Qib
Qin
Qim

Qoq
Qow
Qor
Qot
Qoy
Qop
Qos
Qod
Qof
Qog
Qoh
Qoj
Qok
Qol
Qoz
Qox
Qoc
Qov
Qob
Qon
Qom

Quq
Quw
Qur
Qut
Quy
Qup
Qus
Qud
Quf
Qug
Quh
Quj
Quk
Qul
Quz
Qux
Quc
Quv
Qub
Qun
Qum

[W]

Waq
Waw
War
Wat = "Nước"
Way
Wap
Was
Wad
Waf
Wag
Wah
Waj
Wak
Wal
Waz
Wax
Wac
Wav = "Sóng"
Wab
Wan = "Muốn"
Wam

Weq
Wew
Wer
Wet
Wey
Wep
Wes
Wed
Wef
Weg
Weh
Wej
Wek
Wel
Wez
Wex
Wec
Wev
Web
Wen
Wem

Wiq
Wiw
Wir
Wit
Wiy
Wip
Wis
Wid
Wif
Wig
Wih
Wij
Wik
Wil
Wiz
Wix
Wic
Wiv
Wib
Win = "Gió"
Wim

Woq
Wow
Wor = "Làm việc"
Wot
Woy
Wop
Wos
Wod
Wof
Wog
Woh
Woj
Wok
Wol
Woz
Wox
Woc
Wov
Wob
Won
Wom

Wuq
Wuw
Wur
Wut
Wuy
Wup
Wus
Wud
Wuf
Wug
Wuh
Wuj
Wuk
Wul
Wuz
Wux
Wuc
Wuv
Wub
Wun
Wum

[E]

E

[R]

Raq
Raw
Rar
Rat
Ray
Rap
Ras
Rad
Raf
Rag
Rah
Raj
Rak
Ral = "Rồi"
Raz
Rax
Rac
Rav
Rab
Ran
Ram

Req
Rew
Rer
Ret = "Sinh vật"
Rey
Rep
Res
Red
Ref
Reg
Reh
Rej
Rek
Rel
Rez
Rex
Rec = "Phục hồi"
Rev
Reb
Ren
Rem

Riq
Riw
Rir
Rit
Riy
Rip
Ris
Rid
Rif
Rig = "Sáng"
Rih
Rij
Rik
Ril
Riz
Rix
Ric
Riv
Rib
Rin = "Uống"
Rim

Roq
Row
Ror
Rot
Roy
Rop
Ros
Rod
Rof
Rog
Roh
Roj
Rok
Rol
Roz
Rox
Roc
Rov
Rob
Ron = "Mặt đất"
Rom

Ruq
Ruw
Rur
Rut
Ruy
Rup
Rus
Rud
Ruf
Rug
Ruh
Ruj
Ruk
Rul
Ruz
Rux
Ruc
Ruv
Rub
Run
Rum

[T]

Taq
Taw
Tar = "Nhân tạo"
Tat
Tay
Tap
Tas
Tad
Taf
Tag
Tah
Taj
Tak
Tal
Taz
Tax
Tac
Tav
Tab
Tan = "Đứng yên"
Tam

Teq
Tew
Ter
Tet
Tey
Tep
Tes
Ted
Tef
Teg
Teh
Tej
Tek
Tel
Tez
Tex
Tec
Tev
Teb
Ten
Tem

Tiq
Tiw
Tir
Tit
Tiy
Tip
Tis
Tid
Tif
Tig
Tih
Tij
Tik
Til
Tiz
Tix
Tic
Tiv
Tib
Tin
Tim = "Thời gian"

Toq
Tow
Tor
Tot
Toy
Top
Tos
Tod
Tof
Tog
Toh
Toj
Tok
Tol
Toz
Tox
Toc
Tov
Tob
Ton
Tom

Tuq
Tuw
Tur
Tut
Tuy
Tup
Tus
Tud
Tuf
Tug
Tuh
Tuj
Tuk
Tul
Tuz
Tux
Tuc
Tuv
Tub
Tun
Tum

[Y]

Yaq
Yaw
Yar
Yat
Yay
Yap
Yas
Yad
Yaf
Yag
Yah
Yaj
Yak
Yal
Yaz
Yax
Yac
Yav
Yab
Yan
Yam

Yeq
Yew
Yer = "Tạm biệt"
Yet
Yey
Yep
Yes
Yed
Yef
Yeg
Yeh
Yej
Yek
Yel
Yez
Yex
Yec
Yev
Yeb
Yen
Yem

Yiq
Yiw
Yir
Yit
Yiy
Yip
Yis
Yid
Yif
Yig
Yih
Yij
Yik
Yil
Yiz
Yix
Yic
Yiv
Yib
Yin
Yim

Yoq
Yow
Yor
Yot
Yoy
Yop
Yos
Yod
Yof
Yog
Yoh
Yoj
Yok
Yol
Yoz
Yox
Yoc
Yov
Yob
Yon
Yom
Yuq
Yuw
Yur
Yut
Yuy
Yup
Yus
Yud
Yuf
Yug
Yuh
Yuj
Yuk
Yul
Yuz
Yux
Yuc
Yuv
Yub
Yun
Yum

[U]

U = "Bạn"

[I]

I = "Tôi"

[O]

O

[P]

Paq
Paw
Par
Pat
Pay
Pap
Pas
Pad
Paf
Pag
Pah
Paj
Pak
Pal
Paz
Pax
Pac = "Không gian"
Pav
Pab
Pan
Pam

Peq
Pew
Per
Pet
Pey
Pep = "Người"
Pes
Ped
Pef
Peg
Peh
Pej
Pek
Pel
Pez
Pex
Pec
Pev
Peb
Pen
Pem

Piq
Piw
Pir
Pit
Piy
Pip
Pis
Pid
Pif
Pig
Pih
Pij
Pik
Pil
Piz
Pix
Pic
Piv
Pib
Pin
Pim

Poq
Pow
Por
Pot
Poy
Pop
Pos
Pod
Pof
Pog
Poh
Poj
Pok
Pol
Poz
Pox
Poc
Pov
Pob
Pon
Pom

Puq
Puw
Pur
Put
Puy
Pup
Pus
Pud
Puf
Pug
Puh
Puj
Puk
Pul
Puz
Pux
Puc
Puv
Pub
Pun
Pum

[A]

A

[S]

Saq
Saw
Sar = "Không"
Sat = "Ăn"
Say
Sap
Sas
Sad
Saf = "An toàn"
Sag = "Cơ quan"
Sah
Saj
Sak
Sal
Saz
Sax
Sac
Sav
Sab
San = "Giận"
Sam

Seq
Sew
Ser = "Biển"
Set
Sey
Sep
Ses
Sed
Sef
Seg
Seh
Sej
Sek
Sel
Sez
Sex
Sec
Sev
Seb
Sen
Sem

Siq
Siw
Sir
Sit
Siy
Sip
Sis
Sid
Sif
Sig
Sih
Sij
Sik
Sil
Siz
Six
Sic
Siv
Sib
Sin
Sim

Soq
Sow
Sor
Sot
Soy
Sop
Sos
Sod
Sof
Sog
Soh
Soj
Sok
Sol = "Rắn"
Soz
Sox
Soc
Sov
Sob
Son
Som

Suq
Suw
Sur
Sut
Suy
Sup
Sus
Sud
Suf
Sug
Suh
Suj
Suk
Sul
Suz
Sux
Suc
Suv
Sub
Sun
Sum

[D]

Daq
Daw
Dar
Dat
Day
Dap
Das
Dad
Daf
Dag
Dah
Daj
Dak
Dal
Daz
Dax
Dac
Dav
Dab
Dan = "Nguy hiểm"
Dam

Deq
Dew
Der
Det
Dey
Dep
Des
Ded
Def
Deg
Deh
Dej
Dek
Del
Dez
Dex
Dec
Dev
Deb
Den
Dem

Diq
Diw
Dir
Dit
Diy
Dip
Dis
Did
Dif
Dig
Dih
Dij
Dik
Dil
Diz
Dix
Dic
Div
Dib
Din
Dim

Doq
Dow
Dor
Dot
Doy
Dop
Dos
Dod
Dof
Dog
Doh
Doj
Dok
Dol
Doz
Dox
Doc
Dov
Dob
Don
Dom

Duq
Duw
Dur
Dut
Duy
Dup
Dus
Dud
Duf
Dug
Duh
Duj
Duk
Dul
Duz
Dux
Duc
Duv
Dub
Dun
Dum

[F]

Faq
Faw
Far
Fat
Fay
Fap
Fas = "Nhanh"
Fad
Faf
Fag
Fah
Faj
Fak
Fal
Faz
Fax
Fac
Fav
Fab
Fan
Fam

Feq
Few
Fer
Fet
Fey
Fep
Fes
Fed
Fef
Feg
Feh
Fej
Fek
Fel
Fez
Fex
Fec
Fev
Feb
Fen
Fem

Fiq
Fiw
Fir = "Lửa"
Fit
Fiy
Fip
Fis
Fid
Fif
Fig
Fih
Fij
Fik
Fil
Fiz
Fix
Fic
Fiv
Fib
Fin
Fim

Foq
Fow
For
Fot
Foy
Fop
Fos
Fod
Fof
Fog
Foh
Foj
Fok
Fol
Foz
Fox
Foc
Fov
Fob
Fon
Fom

Fuq
Fuw
Fur
Fut
Fuy
Fup
Fus
Fud
Fuf
Fug
Fuh
Fuj
Fuk
Ful
Fuz
Fux
Fuc
Fuv
Fub
Fun = "Vui"
Fum

[G]

Gaq
Gaw
Gar
Gat
Gay
Gap
Gas
Gad
Gaf
Gag
Gah
Gaj
Gak
Gal
Gaz
Gax
Gac
Gav
Gab
Gan
Gam

Geq
Gew
Ger
Get
Gey
Gep
Ges
Ged
Gef
Geg
Geh
Gej
Gek
Gel
Gez
Gex
Gec
Gev
Geb
Gen
Gem

Giq
Giw
Gir
Git
Giy
Gip
Gis
Gid
Gif
Gig
Gih
Gij
Gik
Gil
Giz
Gix
Gic
Giv
Gib
Gin
Gim

Goq
Gow
Gor
Got
Goy
Gop = "Đi"
Gos
God
Gof
Gog
Goh
Goj
Gok
Gol
Goz
Gox
Goc
Gov
Gob
Gon
Gom

Guq
Guw
Gur
Gut
Guy
Gup
Gus
Gud
Guf
Gug
Guh
Guj
Guk
Gul
Guz
Gux
Guc
Guv
Gub
Gun
Gum

[H]

Haq
Haw
Har
Hat
Hay
Hap
Has
Had
Haf
Hag
Hah
Haj
Hak
Hal
Haz
Hax
Hac
Hav
Hab
Han
Ham

Heq
Hew
Her = "Anh ấy"
Het
Hey
Hep
Hes = "Cô ấy"
Hed
Hef
Heg
Heh
Hej
Hek
Hel = "Xin chào"
Hez
Hex
Hec
Hev = "Nặng"
Heb
Hen
Hem

Hiq
Hiw = "Tại sao"
Hir
Hit
Hiy
Hip
His
Hid
Hif
Hig
Hih
Hij
Hik
Hil
Hiz
Hix
Hic
Hiv
Hib
Hin
Him

Hoq
How
Hor
Hot = "Nóng"
Hoy
Hop
Hos
Hod
Hof
Hog
Hoh
Hoj
Hok
Hol
Hoz
Hox
Hoc
Hov
Hob
Hon
Hom

Huq
Huw
Hur
Hut
Huy
Hup
Hus
Hud
Huf
Hug
Huh
Huj
Huk
Hul
Huz
Hux
Huc
Huv
Hub
Hun
Hum

[J]

Jaq
Jaw
Jar
Jat
Jay
Jap
Jas
Jad
Jaf
Jag
Jah
Jaj
Jak
Jal
Jaz
Jax
Jac
Jav
Jab
Jan
Jam

Jeq
Jew
Jer
Jet
Jey
Jep
Jes
Jed
Jef
Jeg
Jeh
Jej
Jek
Jel
Jez
Jex
Jec
Jev
Jeb
Jen
Jem

Jiq
Jiw
Jir
Jit
Jiy
Jip
Jis
Jid
Jif
Jig
Jih
Jij
Jik
Jil
Jiz
Jix
Jic
Jiv
Jib
Jin
Jim

Joq
Jow
Jor
Jot
Joy
Jop
Jos
Jod
Jof
Jog
Joh
Joj
Jok
Jol
Joz
Jox
Joc
Jov
Job
Jon
Jom

Juq
Juw
Jur
Jut
Juy
Jup
Jus
Jud
Juf
Jug
Juh
Juj
Juk
Jul
Juz
Jux
Juc
Juv
Jub
Jun
Jum

[K]

Kaq
Kaw
Kar
Kat
Kay
Kap
Kas = "Hỏi"
Kad
Kaf
Kag
Kah
Kaj
Kak
Kal
Kaz
Kax
Kac
Kav
Kab
Kan
Kam

Keq
Kew
Ker
Ket
Key
Kep
Kes
Ked
Kef
Keg
Keh
Kej
Kek
Kel
Kez
Kex
Kec
Kev
Keb
Ken
Kem

Kiq
Kiw
Kir
Kit
Kiy
Kip
Kis
Kid
Kif
Kig
Kih
Kij
Kik
Kil
Kiz
Kix
Kic
Kiv
Kib
Kin
Kim

Koq
Kow
Kor
Kot
Koy
Kop
Kos
Kod
Kof
Kog
Koh
Koj
Kok
Kol
Koz
Kox
Koc
Kov
Kob
Kon
Kom

Kuq
Kuw
Kur
Kut
Kuy
Kup
Kus
Kud
Kuf
Kug
Kuh
Kuj
Kuk
Kul
Kuz
Kux
Kuc
Kuv
Kub
Kun
Kum

[L]

Laq
Law
Lar
Lat
Lay
Lap
Las
Lad
Laf
Lag
Lah
Laj
Lak
Lal
Laz
Lax
Lac
Lav
Lab
Lan
Lam

Leq
Lew
Ler
Let
Ley
Lep
Les
Led
Lef
Leg
Leh
Lej
Lek
Lel
Lez
Lex
Lec
Lev
Leb
Len
Lem

Liq = "Chất lỏng"
Liw
Lir
Lit
Liy
Lip
Lis
Lid
Lif = "Bay"
Lig
Lih
Lij
Lik
Lil
Liz
Lix
Lic
Liv
Lib
Lin
Lim

Loq
Low
Lor
Lot
Loy
Lop
Los
Lod
Lof
Log
Loh
Loj
Lok
Lol
Loz
Lox
Loc
Lov
Lob
Lon = "Dài"
Lom

Luq
Luw
Lur
Lut
Luy
Lup
Lus
Lud
Luf
Lug
Luh
Luj
Luk
Lul
Luz
Lux
Luc
Luv
Lub
Lun
Lum

[Z]

Zaq
Zaw
Zar
Zat
Zay
Zap
Zas
Zad
Zaf
Zag
Zah
Zaj
Zak
Zal
Zaz
Zax
Zac
Zav
Zab
Zan
Zam

Zeq
Zew
Zer
Zet
Zey
Zep
Zes
Zed
Zef
Zeg
Zeh
Zej
Zek
Zel
Zez
Zex
Zec
Zev
Zeb
Zen
Zem

Ziq
Ziw
Zir
Zit
Ziy
Zip
Zis
Zid
Zif
Zig
Zih
Zij
Zik
Zil
Ziz
Zix
Zic
Ziv
Zib
Zin
Zim

Zoq
Zow
Zor
Zot
Zoy
Zop
Zos
Zod
Zof
Zog
Zoh
Zoj
Zok
Zol
Zoz
Zox
Zoc
Zov
Zob
Zon
Zom

Zuq
Zuw
Zur
Zut
Zuy
Zup
Zus
Zud
Zuf
Zug
Zuh
Zuj
Zuk
Zul
Zuz
Zux
Zuc
Zuv
Zub
Zun
Zum

[X]

Xaq
Xaw
Xar
Xat
Xay
Xap
Xas
Xad
Xaf
Xag
Xah
Xaj
Xak
Xal
Xaz
Xax
Xac
Xav
Xab
Xan
Xam

Xeq
Xew
Xer
Xet
Xey
Xep
Xes
Xed
Xef
Xeg
Xeh
Xej
Xek
Xel
Xez
Xex
Xec
Xev
Xeb
Xen
Xem

Xiq
Xiw
Xir
Xit
Xiy
Xip
Xis
Xid
Xif
Xig
Xih
Xij
Xik
Xil
Xiz
Xix
Xic
Xiv
Xib
Xin
Xim

Xoq
Xow
Xor
Xot
Xoy
Xop
Xos
Xod
Xof
Xog
Xoh
Xoj
Xok
Xol
Xoz
Xox
Xoc
Xov
Xob
Xon
Xom

Xuq
Xuw
Xur
Xut
Xuy
Xup
Xus
Xud
Xuf
Xug
Xuh
Xuj
Xuk
Xul
Xuz
Xux
Xuc
Xuv
Xub
Xun
Xum

[C]

Caq
Caw
Car = "Sợ"
Cat
Cay
Cap
Cas
Cad
Caf
Cag
Cah
Caj
Cak
Cal
Caz
Cax
Cac = "Nơi ở"
Cav
Cab
Can
Cam

Ceq
Cew
Cer
Cet
Cey
Cep
Ces
Ced
Cef
Ceg
Ceh
Cej
Cek
Cel
Cez
Cex
Cec
Cev
Ceb
Cen
Cem

Ciq
Ciw
Cir
Cit
Ciy
Cip
Cis
Cid
Cif
Cig
Cih
Cij
Cik
Cil
Ciz
Cix
Cic
Civ
Cib
Cin
Cim

Coq
Cow
Cor
Cot
Coy
Cop
Cos
Cod
Cof
Cog
Coh
Coj
Cok
Col = "Màu"
Coz
Cox
Coc
Cov
Cob
Con
Com

Cuq
Cuw
Cur
Cut
Cuy
Cup
Cus
Cud
Cuf
Cug
Cuh
Cuj
Cuk
Cul
Cuz
Cux
Cuc
Cuv
Cub
Cun
Cum

[V]

Vaq
Vaw
Var
Vat
Vay
Vap
Vas
Vad
Vaf
Vag
Vah
Vaj
Vak
Val
Vaz
Vax
Vac
Vav
Vab
Van
Vam

Veq
Vew
Ver
Vet
Vey
Vep
Ves
Ved
Vef
Veg
Veh
Vej
Vek
Vel
Vez
Vex
Vec
Vev
Veb
Ven
Vem

Viq
Viw
Vir
Vit
Viy
Vip
Vis
Vid
Vif
Vig
Vih
Vij
Vik
Vil
Viz
Vix
Vic
Viv
Vib
Vin
Vim

Voq
Vow
Vor
Vot
Voy
Vop
Vos
Vod
Vof
Vog
Voh
Voj
Vok
Vol
Voz
Vox
Voc
Vov
Vob
Von
Vom

Vuq
Vuw
Vur
Vut
Vuy
Vup
Vus
Vud
Vuf
Vug
Vuh
Vuj
Vuk
Vul
Vuz
Vux
Vuc
Vuv
Vub
Vun
Vum

[B]

Baq
Baw
Bar
Bat
Bay
Bap
Bas
Bad
Baf
Bag
Bah
Baj
Bak
Bal
Baz
Bax
Bac
Bav
Bab
Ban
Bam

Beq
Bew
Ber
Bet
Bey
Bep
Bes
Bed
Bef
Beg
Beh
Bej
Bek
Bel
Bez
Bex
Bec
Bev
Beb
Ben
Bem

Biq
Biw
Bir
Bit
Biy
Bip
Bis
Bid
Bif
Big = "Lớn"
Bih
Bij
Bik
Bil
Biz
Bix
Bic
Biv
Bib
Bin
Bim

Boq
Bow
Bor
Bot
Boy
Bop
Bos
Bod = "Cơ thể"
Bof
Bog
Boh
Boj
Bok
Bol
Boz
Box
Boc
Bov
Bob
Bon
Bom

Buq
Buw
Bur
But
Buy
Bup
Bus
Bud
Buf
Bug
Buh
Buj
Buk
Bul
Buz
Bux
Buc
Buv
Bub
Bun
Bum

[N]

Naq
Naw
Nar
Nat
Nay
Nap
Nas
Nad
Naf
Nag
Nah
Naj
Nak
Nal
Naz
Nax
Nac
Nav
Nab
Nan
Nam

Neq
New
Ner
Net
Ney
Nep
Nes
Ned
Nef
Neg
Neh
Nej
Nek
Nel
Nez
Nex
Nec
Nev
Neb
Nen
Nem

Niq
Niw
Nir
Nit
Niy
Nip
Nis
Nid
Nif
Nig
Nih
Nij
Nik
Nil
Niz
Nix
Nic
Niv
Nib
Nin
Nim

Noq
Now
Nor
Not
Noy
Nop
Nos
Nod
Nof
Nog
Noh
Noj
Nok
Nol
Noz
Nox
Noc
Nov
Nob
Non
Nom

Nuq
Nuw
Nur
Nut
Nuy
Nup
Nus
Nud
Nuf
Nug
Nuh
Nuj
Nuk
Nul
Nuz
Nux
Nuc
Nuv
Nub
Nun
Num

[M]

Maq
Maw
Mar = "Thông minh"
Mat
May
Map
Mas
Mad
Maf
Mag
Mah
Maj
Mak
Mal
Maz
Max
Mac
Mav
Mab
Man
Mam

Meq
Mew
Mer
Met
Mey
Mep
Mes
Med
Mef
Meg
Meh
Mej
Mek
Mel
Mez
Mex
Mec = "Cơ khí"
Mev
Meb
Men
Mem

Miq
Miw
Mir
Mit
Miy
Mip
Mis
Mid
Mif
Mig
Mih
Mij
Mik
Mil
Miz
Mix
Mic
Miv
Mib
Min
Mim

Moq
Mow
Mor
Mot
Moy
Mop
Mos
Mod
Mof
Mog
Moh
Moj
Mok
Mol
Moz
Mox
Moc
Mov = "Tiến tới"
Mob
Mon
Mom

Muq
Muw
Mur
Mut
Muy
Mup
Mus
Mud
Muf
Mug
Muh
Muj
Muk
Mul
Muz
Mux
Muc
Muv
Mub
Mun
Mum