#Language: 

[W]
We = "Nước"
Wa = "Gì/Là gì/Cái gì"
Wi = "Với/Cùng"
Wo = "Tệ/Xấu"
Wu = "Sợ"

[E]
Eq = "Bằng"
Et = "Ăn"
Ex = "Trao đổi"
En = "Năng lượng"
Em = "Ngôi thứ nhất"
Ef = "Hiệu quả"
Ed = "Giáo dục"
Er = "Lỗi"
El = "Lựa chọn"
Ew = "Mắt"
Ec = "Dòng/Chảy"
Es = "Bản chất"
Ep = "Kỳ vọng"

[R]
Re = "Phục hồi/Chữa trị"
Ru = "Lí do/Nguyên nhân"
Ri = "Thực tế/Sự thật"
Ra = "Nhanh"
Ro = "Quay/Xoay"

[T]
Te = "Công nghệ"
Ti = "Thời gian"
Ta = "Bàn/Cái"
To = "Cao"
Tu = "Học"

[Y]
Yu = "Ngôi thứ hai"
Ya = "Có"
Ye = "Năm"
Yo = "Bạn"
Yi = "Đúng"

[U]
Un = "Hiểu"
Up = "Lên"
Us = "Chúng tôi"
Ud = "Xuống"
Ub = "Trên lòng"

[I]
Iq = "Trong"
It = "Ngôi thứ ba"
Ib = "Tại"
In = "Thông tin"
Im = "Ngôi thứ nhất (khác)"
Ik = "Bệnh/Ốm"
Id = "Ý tưởng"
Is = "Là"

[O]
Ow = "Sở hữu"
Or = "Hoặc"
Ox = "Oxy"
Od = "Lạ/Kỳ"
Of = "Của"
Oh = "Lỗ"
Ol = "Cũ"
Om = "Ôm"
On = "Trên"

[P]
Pa = "Bộ phận"
Pe = "Người"
Pi = "Phi (π)"
Po = "Sức mạnh"
Pu = "Tinh khiết"

[A]
Ar = "Nhân tạo"
At = "Đến"
Aw = "Không khí"
Ac = "Nơi ở"
Ab = "Trên"
An = "Và"
Ae = "Kinh hãi"
Al = "Tất cả"
Ad = "Thêm"
Ap = "Áp dụng"
As = "Hỏi"

[S]
Se = "Không gian"
Su = "An toàn"
Si = "Đứng yên"
So = "Chất rắn"
Sa = "Thông minh"

[D]
Di = "Uống"
Da = "Dữ liệu"
De = "Chết"
Do = "Làm"
Du = "Lâu"

[F]
Fi = "Bay"
Fo = "Lửa"
Fa = "Nhanh"
Fe = "Cảm giác"
Fu = "Đầy/Toàn"

[G]
Go = "Đi"
Ge = "Định dạng/Hình dạng"
Gu = "Bảo vệ"
Ga = "Khí"

[H]
He = "Xin chào"
Hu = "Con người"
Hi = "Cao"
Ha = "Vui/Hạnh phúc"
Ho = "Nhà"

[K]
Ko = "Biết"
Ka = "Bắt đầu"
Ke = "Chìa khóa"
Ki = "Giết"

[L]
Li = "Ánh sáng"
La = "Lớn"
Le = "Để/Để cho"
Lo = "Khóa"
Lu = "Sung sướng"

[C]
Ce = "Sinh vật"
Co = "Cộng đồng"
Ca = "Có thể"
Ci = "Thành phố"
Cu = "Cắt"

[V]
Va = "Giá trị/Chất lượng"
Ve = "Rất"
Vi = "Không nhìn thấy"
Vo = "Giọng nói"
Vu = "Giả vờ"

[B]
Be = "Trước"
Bi = "Lớn"
Ba = "Bẫm/Dừng lại"
Bo = "Xương"
Bu = "Xây dựng"

[N]
Na = "Tên"
Ne = "Mạng lưới"
Ni = "Không/Hiện không"
No = "Số"
Nu = "Mới"

[M]
Me = "Cách thức/Phương pháp"
Mu = "Có thể"
Ma = "Máy móc"
Mi = "Bé nhỏ"
Mo = "Chuyển động"
